### ISSUE TITLE
C++ Syntax Error on "const" parameter

### ISSUE THREAD

**Issue by morris821028** [voutcn/kxsort#1]
Hi all,

I'm not good at C++. But I try to sort pointer array to let it increase in address value. I encountered the compiler error log about "constant variable".

```cpp
#include <vector>
#include <utility> // for pair
#include <algorithm>
#include <iostream>
#include <cstdlib>
#include <ctime>
#include "kxsort.h"
using namespace std;

struct Data {
    int32_t v[4];
};
struct Node {
    Node *next;
    Data dat;
};

struct PointerRadixTraits {
    static const int nBytes = sizeof(Node*);
    int kth_byte(Node* const &x, int k) {
        return (uint64_t) x >> (k * 8) & 0xFF;
    }
    bool compare(Node* const &x, Node* const &y) {
        return x < y;
    }
};

vector<Node*> gen(int N) {
	vector<Node*> v(N);
	for (int i = 0; i < N; ++i)
	    v[i] = (Node*) malloc(sizeof(Node));
	return v;
}

int main() {
	int N = 10000000;
	srand(time(NULL));
	vector<Node*> v = gen(N);
	kx::radix_sort(v.begin(), v.end(), PointerRadixTraits());
	cout << is_sorted(v.begin(), v.end()) << endl;
	return 0;
}
```

I think the reference temporary make compiler hint is not toward `const reference`. Did we write as follows. To add the constant temporary variable.

```cpp
template <class RandomIt, class ValueType, class RadixTraits>
inline void insert_sort_core_(RandomIt s, RandomIt e, RadixTraits radix_traits)
{
    for (RandomIt i = s + 1; i < e; ++i) {
        const ValueType a = *i; const ValueType b = *(i-1); // enforce ?
        if (radix_traits.compare(a, b)) {
```

When you write as `bool compare(const Node* &x, const Node* &y);` or `bool compare(Node* &x, Node* &y)`, the compiler will gives you

```
[Error] no matching function for call to 'PointerRadixTraits::compare(Node* const&, Node* const&)'
```

not 

```
[Error] no matching function for call to 'PointerRadixTraits::compare(Node*&, Node*&)'
```

How do you think?

Thanks

**Comment by Kobzol** [comment]
Your posted code compiles with `g++ 7.3.0` using the C++14 standard.
